name: Build and deploy Node.js app to Azure Web App - FlashCards-maenau

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x" # Utilise la v20 LTS, plus stable pour Adonis 6

      - name: Install dependencies
        run: |
          cd P_Bulles-Flashcard
          cd app-flashcards-adonisjs
          npm ci

      - name: Build project
        run: |
          cd P_Bulles-Flashcard
          cd app-flashcards
          node ace build

      - name: Prepare Deployment Folder
        run: |
          cd P_Bulles-Flashcard
          cd app-flashcards
          cd build
          npm ci --omit=dev

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          # On n'envoie que le CONTENU du dossier build
          # Ainsi, bin/server.js sera Ã  la racine de wwwroot sur Azure
          path: app-flashcards/build/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "FlashCards-maenau"
          slot-name: "Production"
          package: . # Ici '.' correspond maintenant au contenu de build/
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C40DA6533DAD4682B6CA38C131AB2E9F }}